<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="8" total="9" passed="0">
  <reporter-output>
    <line>
      <![CDATA[username provided]]>
    </line>
    <line>
      <![CDATA[password provided]]>
    </line>
    <line>
      <![CDATA[Submit button clicked]]>
    </line>
    <line>
      <![CDATA[Icon clicked]]>
    </line>
    <line>
      <![CDATA[Move to Activities]]>
    </line>
    <line>
      <![CDATA[test case failed....]]>
    </line>
  </reporter-output>
  <suite name="DashManagement" duration-ms="12115" started-at="2019-11-26T22:57:39Z" finished-at="2019-11-26T22:57:51Z">
    <groups>
    </groups>
    <test name="Priority Test" duration-ms="12115" started-at="2019-11-26T22:57:39Z" finished-at="2019-11-26T22:57:51Z">
      <class name="com.projects.activities.testCases.TC_ProgramPriorityTest_002">
        <test-method status="PASS" signature="extentSetup(org.testng.ITestContext)[pri:0, instance:com.projects.activities.testCases.TC_ProgramPriorityTest_002@3c0ecd4b]" name="extentSetup" is-config="true" duration-ms="119" started-at="2019-11-26T16:57:39Z" finished-at="2019-11-26T16:57:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@10993713]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentSetup -->
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.projects.activities.testCases.TC_ProgramPriorityTest_002@3c0ecd4b]" name="setup" is-config="true" duration-ms="4336" started-at="2019-11-26T16:57:39Z" finished-at="2019-11-26T16:57:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="startExtent(java.lang.reflect.Method, [Ljava.lang.Object;)[pri:0, instance:com.projects.activities.testCases.TC_ProgramPriorityTest_002@3c0ecd4b]" name="startExtent" is-config="true" duration-ms="4" started-at="2019-11-26T16:57:44Z" finished-at="2019-11-26T16:57:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.projects.activities.testCases.TC_ProgramPriorityTest_002.validateProgramId() throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.Object;@3fffff43]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startExtent -->
        <test-method status="FAIL" signature="validateProgramId()[pri:0, instance:com.projects.activities.testCases.TC_ProgramPriorityTest_002@3c0ecd4b]" name="validateProgramId" duration-ms="6907" started-at="2019-11-26T16:57:44Z" finished-at="2019-11-26T16:57:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at com.projects.activities.testCases.TC_ProgramPriorityTest_002.validateProgramId(TC_ProgramPriorityTest_002.java:189)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[username provided]]>
            </line>
            <line>
              <![CDATA[password provided]]>
            </line>
            <line>
              <![CDATA[Submit button clicked]]>
            </line>
            <line>
              <![CDATA[Icon clicked]]>
            </line>
            <line>
              <![CDATA[Move to Activities]]>
            </line>
            <line>
              <![CDATA[test case failed....]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateProgramId -->
        <test-method status="PASS" signature="afterEachTestMethod(org.testng.ITestResult)[pri:0, instance:com.projects.activities.testCases.TC_ProgramPriorityTest_002@3c0ecd4b]" name="afterEachTestMethod" is-config="true" duration-ms="847" started-at="2019-11-26T16:57:51Z" finished-at="2019-11-26T16:57:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateProgramId status=FAILURE method=TC_ProgramPriorityTest_002.validateProgramId()[pri:0, instance:com.projects.activities.testCases.TC_ProgramPriorityTest_002@3c0ecd4b] output=username provided]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEachTestMethod -->
        <test-method status="PASS" signature="generateReport()[pri:0, instance:com.projects.activities.testCases.TC_ProgramPriorityTest_002@3c0ecd4b]" name="generateReport" is-config="true" duration-ms="20" started-at="2019-11-26T16:57:51Z" finished-at="2019-11-26T16:57:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReport -->
      </class> <!-- com.projects.activities.testCases.TC_ProgramPriorityTest_002 -->
    </test> <!-- Priority Test -->
  </suite> <!-- DashManagement -->
</testng-results>
